name: Cross-Compile for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install MinGW
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64 cmake make

    - name: Create toolchain file
      run: |
        cat > windows-toolchain.cmake << 'EOF'
        set(CMAKE_SYSTEM_NAME Windows)
        set(CMAKE_SYSTEM_PROCESSOR x86_64)
        set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
        set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
        set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)
        set(CMAKE_FIND_ROOT_PATH /usr/x86_64-w64-mingw32)
        set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
        set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
        set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
        EOF

    - name: Configure and Build
      run: |
        rm -rf build
        mkdir build
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=../windows-toolchain.cmake -G "Unix Makefiles"
        make

    - name: Upload Windows executable
      uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: build/*.exe