name: Cross-Compile for Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@v3

    - name: Install MinGW
      run: sudo apt-get install -y mingw-w64

    - name: Create toolchain file
      run: |
        echo 'set(CMAKE_SYSTEM_NAME Windows)' > toolchain.cmake
        echo 'set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)' >> toolchain.cmake
        echo 'set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)' >> toolchain.cmake
        echo 'set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)' >> toolchain.cmake
        echo 'set(CMAKE_FIND_ROOT_PATH /usr/x86_64-w64-mingw32)' >> toolchain.cmake
        echo 'set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)' >> toolchain.cmake
        echo 'set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)' >> toolchain.cmake
        echo 'set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)' >> toolchain.cmake

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=toolchain.cmake

    - name: Build
      run: cmake --build build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-executable
        path: build/*.exe