name: Cross-Compile for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Cross-Compile to Windows
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake mingw-w64 make

    - name: Create toolchain file
      run: |
        cat > windows-toolchain.cmake << EOF
        set(CMAKE_SYSTEM_NAME Windows)
        set(CMAKE_SYSTEM_PROCESSOR x86_64)
        
        set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
        set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
        
        set(CMAKE_FIND_ROOT_PATH /usr/x86_64-w64-mingw32)
        set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
        set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
        set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
        EOF

    - name: Configure project with CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=../windows-toolchain.cmake

    - name: Build project
      run: |
        cd build
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: GraphIsomorphismChecker
        path: build/GraphIsomorphismChecker.exe